dataset:
  name: 'cifar10'
  path: './data/cifar10'
  size: 32
evaluation:
  data:
    - bsz: 50
      name: 'cifar10'
      path: './data/cifar10'
      size: 32
experiment: 'ImageGeneration'
model:
  G: 'ConvGenerator32'
  D: 'SNDiscriminator32'
  opt: 'Adam'
  opt_param:
    lr: 2.0e-4
    betas:
      - 0.5
      - 0.999
  type: 'DCGAN'
hparam:
  bsz: 64
  iteration: 100000
log:
  freq: 1000
  path: './log/DCGAN-BASE-CIFAR10-C'
protection: null
resource:  
  gpu: true
  ngpu: 1
  worker: 4
seed: 7890