dataset:
  name: 'horse2zebra'
  path: '../../datasets/horse2zebra'
  load: 143
  crop: 128
evaluation:
  p_thres: 0.05
  data:
    - bsz: 1
      name: 'horse2zebra'
      path: '../../datasets/horse2zebra'
      load: 256
      crop: 256
experiment: 'ImageTranslation'
model:
  G: 'CUTResnetGenerator'
  D: 'NLayerDiscriminatorCUT'
  F: 'PatchSampleF'
  lambda_GAN: 1.0
  lambda_NCE: 1.0
  lambda_idt: 0.5
  opt: 'Adam'
  opt_param:
    lr: 2.0e-4
    betas:
      - 0.5
      - 0.999
  pool_size: 50
  type: 'CUT'
hparam:
  bsz: 1
  iteration: 200 # epoch
log:
  freq: 1
  path: './log/CUT-COMP-HORES2ZEBRA-A'
protection:
  bbox:
    fn_inp:
      size: 64
      type: 'RandomNoisePatch'
    fn_out:
      size: 64
      opaque: true
      type: 'PasteWatermark'
      watermark: './data/watermarks/A.png'
    lambda: 1.0
    loss_fn: 'ssim'
  wbox:
    gamma_0: 0.1
    string: 'EXAMPLE A'
resource:  
  gpu: true
  ngpu: 1
  worker: 4
seed: 1234