dataset:
  name: 'CelebA'
  path: '../../datasets/CelebA/Img/img_align_celeba'
  load: 143
  crop: 128
evaluation:
  p_thres: 0.05
  data:
    - bsz: 1
      name: 'CelebA'
      path: '../../datasets/CelebA/Img/img_align_celeba'
      load: 256
      crop: 256
experiment: 'ImageTranslationStarGAN'
model:
  G: 'GeneratorResNet'
  D: 'StarGANDiscriminator'
  lambda_GP: 10.0
  lambda_REC: 10.0
  lambda_CLS: 1
  opt: 'Adam'
  opt_param:
    lr: 2.0e-4
    betas:
      - 0.5
      - 0.999
  # pool_size: 50
  type: 'StarGAN'
hparam:
  bsz: 1
  iteration: 200 # epoch
log:
  freq: 1
  path: './log/StarGAN-COMP-CELEBA-A'
protection:
  bbox:
    fn_inp:
      size: 64
      type: 'RandomNoisePatch'
    fn_out:
      size: 64
      opaque: true
      type: 'PasteWatermark'
      watermark: './data/watermarks/A.png'
    lambda: 1.0
    loss_fn: 'ssim'
  wbox:
    gamma_0: 0.1
    string: 'EXAMPLE A'
resource:  
  gpu: true
  ngpu: 2
  worker: 4
seed: 1234