dataset:
  name: 'cub200'
  path: './data/cub200'
  size: 64
evaluation:
  data:
    - bsz: 50
      name: 'cub200'
      path: './data/cub200'
      size: 64
experiment: 'ImageGeneration'
model:
  G: 'ConvGenerator64'
  D: 'SNDiscriminator64'
  opt: 'Adam'
  opt_param:
    lr: 2.0e-4
    betas:
      - 0.5
      - 0.999
  type: 'DCGAN'
hparam:
  bsz: 64
  iteration: 100000
log:
  freq: 1000
  path: './log/DCGAN-BASE-CUB200-B'
protection: null
resource:  
  gpu: true
  ngpu: 1
  worker: 4
seed: 4567