from networks.conv_generator import *
from networks.conv_discriminator import *
from networks.discriminator_96 import *
from networks.decoder import *
from networks.encoder import *
from networks.inception import InceptionActivations
from networks.resnet_generator import *
from networks.sn_discriminator import *
from networks.sr_resnet import *
from networks.vgg import *
from networks.starGAN_discriminator import *
from networks.starGAN_generator import *
from networks.attentionv2_generator import *
from networks.attentionv2_discriminator import *
from networks.cut_generator import *
from networks.cut_discriminator import *
from networks.cut_patch_net import PatchSampleF
